### PR TITLE
Use the official `pnpm` based images

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Review by davisagli — COMMENTED** [review]
This will only work if VOLTO_VERSION is 18.0.0-alpha.43 or later

**Comment by sneridagh** [comment]
@davisagli ufff, yes... would anybody use Cookieplone and choose an alpha version that is not the last one? And final is near...
We could put logic in CookiePlone itself for account for this, but would it be worth it?

**Comment by sneridagh** [comment]
@davisagli In the meanwhile, Cookieplone get the images from the ones that the kitconcept repo PR generates... which inherently is bad and forces us to release there a43 too. I would merge this asap.

I would write a post to the community forums, to make people notice of the change.

Overall, Cookieplone was experimental until that we decide that it will be the default in Plone 6.1/Volto 18, so everybody that used it has to adjust to latest anyways... it's like when you use an alpha, then there's a final version.

**Comment by stevepiercy** [comment]
I want to slam on the brakes for two reasons:

1.  We need to prepare docs first before merging this. See
    - https://github.com/plone/documentation/issues/1706
    - https://github.com/plone/volto/issues/6289
    - https://github.com/plone/documentation/issues/1705
2.  There is a discussion about Official Plone Docker issues taking place in Discord and GitHub with Docker staff. See:
    - https://github.com/docker-library/docs/pull/2479
    - https://discord.com/channels/786421998426521600/787390558809096192/1268591927071084689

**Comment by davisagli** [comment]
@stevepiercy I'm doing some testing before commenting here, but for now I'll say:
1. Merging this makes cookieplone-templates better, not worse (it already does not work with volto 16 and 17, and at the moment it does not work with volto 18 until we merge this)
2. We're fully aware that docs are needed, and we need to time that carefully with the final release of Volto 18. I need to catch up with your flurry of issues & PRs from yesterday, and I'm hosting some people today so won't have time to look carefully until later.

I wasn't aware of the discussion on Discord, so I'll have to catch up with that as well.

But no break slamming needed here from my point of view. This PR is about fixing the current image used by cookieplone-templates, not about the efforts to recommend it as a default.

**Comment by davisagli** [comment]
@sneridagh I agree we should go ahead and merge this, but it made me realize that the cookieplone templates don't work with older versions of Volto, which I wasn't aware or had forgotten. This means we'll need to do a much better job of communicating when people can use cookieplone. i.e.
1. It's misleading that cookieplone prompts for a Volto version and accepts older versions, but they don't work. We should validate the version there or at least give some help text about what is supported.
2. When we update docs to explain how to create a project with cookieplone, we have to explain that it's for Volto 18 only, and refer people to cookiecutter-plone-starter if they need to generate a project with an older version.

**Comment by stevepiercy** [comment]
@sneridagh OK, that makes sense.

@davisagli for docs, we need to maintain everything that works with supported versions of Plone, so we'll need two sets of docs for creating a project with Volto. I think we'll need separate pages, or possibly a synchronized tabbed interface thanks to [Sphinx Design](https://sphinx-design.readthedocs.io/en/latest/tabs.html#synchronised-tabs). I'm wary of the length, but with synchronization, it might be OK.

**Comment by davisagli** [comment]
@stevepiercy I agree both with the need and with your wariness about it. I wish we could make a cleaner cut over to a new set of instructions, but the changes are all tied up in the switch to a different way of organizing the frontend code, which only works in Volto 18 and beyond.

I will help with this.

**Review by davisagli — APPROVED** [review]

**Review by ericof — APPROVED** [review]

**Pull request merged**
